### ISSUE TITLE
Compatible database

### ISSUE THREAD

**Issue by jereparemonpc** [Sighmir/vrp_lscustoms#1]
Hi, what database do you use to run add if not exist?

**Comment by Sighmir** [comment]
It works with MySQL, tested with MariaDB.

**Comment by jereparemonpc** [comment]
Thank you ! So I adapt it and it works

**Comment by Sighmir** [comment]
Glad you got it to work! Update for compatibility planned in the future. For now.. MariaDB is the choice I recommend.
