### ISSUE TITLE
Customizations not saving

### ISSUE THREAD

**Issue by WingedHussarr** [Sighmir/vrp_lscustoms#2]
The customisation does not save when vehicle is stored and retrieved. No errors are displayed

**Comment by WingedHussarr** [comment]
This may be linked to this issue: https://github.com/Sighmir/vrp_garages/issues/4

**Comment by Sighmir** [comment]
The resource works fine. An issue named "Does not work" doesnt really tell me much, the cars have to be bought at the vrp_showroom, then you can modify then in the vrp_lscustoms and store them at vrp_garages. vrp_garagges stores the vehicles and save the customizations made on vrp_lscustoms when using vehicles bought at vrp_showroom.
I wouldn't leave the resources on github if they were not working.
