### ISSUE TITLE
Car Customization does not save

### ISSUE THREAD

**Issue by mrCPUgeek** [Sighmir/vrp_lscustoms#4]
When I make changes to a car I own and leave the LS Customs shop, the car looks right, but nothing gets written to the mysql database.  When I pull the car the next time, the mods are gone.

I put "print" lines in both the client.lua and server.lua and it seems to get all the way to where "selectButton" happens, then I don't get any more "print" lines when testing.

Thanks!

**Comment by Sighmir** [comment]
Are you taking your cars out of my vrp_garages? Are you sure the columns were created oh vrp_vehicles? Are you using mariaDB or phpmyadmin? Are you buying the cars from vrp_showroom? Do you get the notification when making changes to the car on top of the map?
Sorry to make that many questions, I need all that information to help you and don't have time to ask one by one.

**Comment by mrCPUgeek** [comment]
Thank you for your reply.  I bought the car from the original vrp_garages.  I just bought one thru the showroom and it works correctly.  I'll remove those other garages now.  Thanks for you help!
