### ISSUE TITLE
SQL Problem! 

### ISSUE THREAD

**Issue by Armagryzor** [Sighmir/vrp_lscustoms#5]
Hi Sir,

Is it possible to change or make the system sql ?

A lot of peoples ( In FiveM Board) and me have some trouble to install your Addon because the Mysql ( i use Navicat ) Don't want or don't like the : ADD IF NOT EXISTS

I s it possible to find an other solution to create the tables like with a sql file!!??!! 

Thank's a lot for your work , i'm a Fan!

**Comment by Sighmir** [comment]
In about 3 months I will release the rewritten version of these scripts: vrp_garages, vrp_lscustoms and vrp_showroom.
So there will be no further modifications to something that will be replaced.

The new version will work with all mysql dbs and it will be an all in one garages/lscustoms/showroom/home system.

I am finishing another semester in University and go back to GTA V scripting in 60 days. I just don't have time at the moment.

**Comment by Armagryzor** [comment]
Thank's a lot !!!

**Comment by Sighmir** [comment]
For now [mariadb.org](mariadb.org) is what I recommend to use my scripts.
